=== hieurobert99/ta-solvd_bank-management_robert-nguyen/src/main/resources/bank.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:complexType name="accountType">
        <xs:all>
            <xs:element name="type" type="xs:string"/>
            <xs:element name="currency" type="xs:string"/>
            <xs:element name="balance" type="xs:decimal"/>
            <xs:element name="customerId" type="xs:long"/>
        </xs:all>
        <xs:attribute name="id" type="xs:long" use="required"/>
    </xs:complexType>

    <xs:complexType name="accountsType">
        <xs:sequence>
            <xs:element name="account" type="accountType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="customerType">
        <xs:all>
            <xs:element name="accounts" type="accountsType"/>
            <xs:element name="firstName" type="xs:string"/>
            <xs:element name="lastName" type="xs:string"/>
            <xs:element name="addressId" type="xs:long"/>
            <xs:element name="bankId" type="xs:long"/>
        </xs:all>
        <xs:attribute name="id" type="xs:long" use="required"/>
    </xs:complexType>

    <xs:complexType name="customersType">
        <xs:sequence>
            <xs:element name="customer" type="customerType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>

    </xs:complexType>

    <xs:complexType name="employeeType">
        <xs:all>
            <xs:element name="firstName" type="xs:string"/>
            <xs:element name="lastName" type="xs:string"/>
            <xs:element name="addressId" type="xs:long"/>
            <xs:element name="bankId" type="xs:long"/>
        </xs:all>
        <xs:attribute name="id" type="xs:long" use="required"/>
    </xs:complexType>

    <xs:complexType name="employeesType">
        <xs:sequence>
            <xs:element name="employee" type="employeeType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="bankType">
        <xs:all>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="addressId" type="xs:long"/>
            <xs:element name="employees" type="employeesType"/>
            <xs:element name="customers" type="customersType"/>
        </xs:all>
        <xs:attribute name="id" type="xs:long" use="required"/>
    </xs:complexType>

    <xs:element name="bank" type="bankType"/>
</xs:schema>

=== hieurobert99/ta-solvd_bank-management_robert-nguyen/src/main/resources/bank.xml
<bank xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="bank.xsd" id="1">

    <name>MBank</name>
    <addressId>1</addressId>
    <employees>
        <employee id="1">
            <firstName>John</firstName>
            <lastName>Smith</lastName>
            <addressId>2</addressId>
            <bankId>1</bankId>
        </employee>
    </employees>
    <customers>
        <customer id="1">
            <firstName>Robert</firstName>
            <lastName>Nguyen</lastName>
            <addressId>3</addressId>
            <bankId>1</bankId>
            <accounts>
                <account id="1">
                    <type>Premium</type>
                    <currency>PLN</currency>
                    <balance>1000</balance>
                    <customerId>1</customerId>
                </account>
            </accounts>
        </customer>
        <customer id="2">
            <firstName>Peter</firstName>
            <lastName>Parker</lastName>
            <addressId>4</addressId>
            <bankId>1</bankId>
            <accounts>
                <account id="2">
                    <type>Standard</type>
                    <currency>USD</currency>
                    <balance>50</balance>
                    <customerId>2</customerId>
                </account>
            </accounts>
        </customer>
    </customers>
</bank>
